# docker compose up --build (first time)
# docker compose up

version: "3"
services:
  server:
    build: ./backend
    ports:
      - "4000:4000"
  client:
    build: ./frontend
    ports:
      - "3000:3000"
