# open -a Docker
# docker compose -f docker-compose.dev.yml up --build (first time)
# docker compose -f docker-compose.dev.yml up

version: "3"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules # ! Don't forget
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # ! Don't forget
    environment:
      - NODE_ENV=development
